apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
        - name: homework
          image: kentmarcus/homework:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:~/H2db/HansabDb;AUTO_SERVER=TRUE;MODE=MySQL"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
